name: Publish Release
on:
  release:
    types:
      - published

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn prepack

      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          if [[ "${{ github.event.release.tag_name }}" == *"beta"* ]]; then
            npm publish --tag beta
          else
            npm publish
          fi
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
